server:
  port: 8080
  compression:
    enabled: true
  servlet:
    context-path: /

management:
  endpoint:
    httptrace:
      enabled: true

  endpoints:
    web:
      exposure:
        include: "health,info,httptrace,metrics,auditevents"
